apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_NAME}-typesense-data
  namespace: ${KUBE_NAMESPACE}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
