apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-typesense
  namespace: ${KUBE_NAMESPACE}
  labels:
    app: ${APP_NAME}-typesense
spec:
  selector:
    app: ${APP_NAME}-typesense
  ports:
    - port: 8108
      targetPort: 8108
  type: ClusterIP
